#!/usr/bin/env node
/**
 * Downloads the Rubik subsets we use (hebrew + latin) from Google Fonts and
 * writes promo/fonts.css with the woff2 files inlined as data URIs.
 *
 * Run once (needs network); the generated fonts.css is committed so that
 * rendering works offline and scene.html can be opened straight from disk.
 *
 *   node promo/tools/build-fonts.mjs
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, '..', 'fonts.css');

const WEIGHTS = [400, 500, 700, 900];
const SUBSETS = ['hebrew', 'latin'];
const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const cssUrl =
  'https://fonts.googleapis.com/css2?family=Rubik:wght@' +
  WEIGHTS.join(';') +
  '&display=block';

const css = await (await fetch(cssUrl, { headers: { 'User-Agent': UA } })).text();

// Google returns blocks of "/* subset */ @font-face { ... }" in source order.
const blocks = [];
const re = /\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g;
for (let m; (m = re.exec(css)); ) blocks.push({ subset: m[1], face: m[2] });

const wanted = blocks.filter((b) => SUBSETS.includes(b.subset));
if (!wanted.length) throw new Error('no matching @font-face blocks found');

const out = ['/* Rubik (hebrew + latin subsets), inlined. Generated by promo/tools/build-fonts.mjs */'];
for (const { subset, face } of wanted) {
  const url = face.match(/url\((https:\/\/[^)]+)\)/)?.[1];
  const weight = face.match(/font-weight:\s*(\d+)/)?.[1];
  const buf = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
  const data = `url(data:font/woff2;base64,${buf.toString('base64')}) format('woff2')`;
  out.push(
    `/* ${subset} ${weight} */`,
    face.replace(/src:\s*url\([^)]+\)\s*format\('woff2'\)/, `src: ${data}`).trim()
  );
  console.log(`  ${subset} ${weight}: ${(buf.length / 1024).toFixed(1)} KB`);
}

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, out.join('\n') + '\n');
console.log(`\nwrote ${OUT}`);
